# Copyright (c) 2026 Brian Fundakowski Feldman.
# Light-ware License — see LICENSE.

.if !defined(SYSDIR)
SYSDIR?=	/usr/src/sys
.endif

KMOD=	pqfreebsd_compat_zfs_multilabel
SRCS=	pqfreebsd_compat_zfs_multilabel.c

.include <bsd.kmod.mk>
