# SPDX-License-Identifier: LicenseRef-Light-ware
#
# Copyright (c) 2026 Brian Fundakowski Feldman

.PATH: ${.CURDIR:H:H}/pqfreebsd

KMOD=	pqfreebsd_compat_zfs_multilabel
SRCS=	${KMOD}.c
SRCS+=	vnode_if.h

.include <bsd.kmod.mk>
